spring.application.name=audit-log-service
spring.datasource.url=jdbc:postgresql://localhost:5432/audit_log
spring.datasource.username=postgres
spring.datasource.password=190786

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
audit.log.genesis-value=audit-log-genesis-v1

server.port=8081

audit.retention.days=365
